import { feetAndInchesToMm } from "@/lib/units";
import { type EstimateInput } from "@/lib/domain/types";

export const fenceDepotProfile = {
  businessName: "Fence Depot",
  addressLine1: "3045 Pitt Street",
  city: "Cornwall",
  province: "Ontario",
  postalCode: "K6K 1A9",
  phone: "613-932-0717",
  email: "fencedepot@hotmail.com",
  defaultHstRateBasisPoints: 1300,
  defaultLinePostSpacingMm: feetAndInchesToMm(10),
  defaultFabricWasteBasisPoints: 500,
  defaultTopRailLengthMm: feetAndInchesToMm(21, 3),
  defaultFootingDiameterMm: feetAndInchesToMm(0, 8),
  defaultFootingDepthMm: feetAndInchesToMm(3, 6),
};

export const demoEstimateInput: EstimateInput = {
  customer: {
    displayName: "Demo Customer - Riverside Yard",
    companyName: "Sample Only",
    email: "demo@example.com",
    phone: "613-555-0100",
  },
  projectSite: {
    siteName: "Demo Chain-Link Estimate",
    addressLine1: "100 Sample Road",
    city: "Cornwall",
    province: "Ontario",
    postalCode: "K6H 0A1",
    notes: "Demo/sample data for the first release.",
  },
  configuration: {
    installationMethod: "CONCRETE_FOOTING",
    linePostSpacingMm: feetAndInchesToMm(10),
    fabricWasteBasisPoints: 500,
    topRailStockLengthMm: feetAndInchesToMm(21, 3),
    footingDiameterMm: feetAndInchesToMm(0, 8),
    footingDepthMm: feetAndInchesToMm(3, 6),
    pricingMode: "MARKUP",
    adjustmentBasisPoints: 2200,
    taxBasisPoints: 1300,
    freightCents: 25000,
    nonStockCents: 18500,
    contingencyBasisPoints: 300,
    labourHours: 18,
    equipmentHours: 6,
    labourRateId: "seed-install-crew",
    equipmentRateId: "seed-auger",
    tieWireSpacingMm: feetAndInchesToMm(1),
    overrideReason: "",
  },
  runs: [
    {
      name: "Perimeter Run A",
      lengthMm: feetAndInchesToMm(120),
      heightMm: feetAndInchesToMm(6),
      endTerminalPosts: 2,
      cornerTerminalPosts: 2,
    },
  ],
  gates: [
    {
      name: "Main Double Gate",
      gateType: "DOUBLE_SWING",
      widthMm: feetAndInchesToMm(12),
      heightMm: feetAndInchesToMm(6),
      quantity: 1,
      includeFrameKit: true,
      overrideReason: "",
    },
  ],
  selections: {
    fabric: "seed-fabric-black-6",
    linePost: "seed-line-post-2-3-8-black",
    terminalPost: "seed-terminal-post-2-7-8-black",
    gatePost: "seed-gate-post-4-black",
    topRail: "seed-top-rail-black",
    tensionBar: "seed-tension-bar",
    tensionBand: "seed-tension-band-black",
    braceBand: "seed-brace-band-black",
    tieWire: "seed-tie-wire-black",
    concrete: "seed-concrete-bag",
    gateHardware: "seed-gate-hardware-double",
    gateFrame: "seed-gate-frame-kit-black",
  },
  overrides: {},
};
